### ISSUE TITLE
Massive API changes (Aug 16, 2018)

### ISSUE THREAD

**Issue by cannorin** [CoreTweet/CoreTweet#160]
Related: #159 #161 #162

## Endpoints going to be deprecated:

- [x] User Streams
- [x] Site Streams
- [x] GET direct_messages
- [x] GET direct_messages/sent
- [x] GET direct_messages/show
- [x] POST direct_messages/new
- [x] POST direct_messages/destroy

## Tasks

- [x] Wait for the approval of Twitter Developer accounts
- [x] Get a server (preferably free) to test webhooks
- [x] Implement [Enterprise Account Activity API](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/aaa-enterprise)
- [x] Implement [Premium Account Activity API](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/aaa-premium)

## Links

* [Account Activity API migration guide](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide)
* [Direct Message migration guide](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration)

**Comment by acid-chicken** [comment]
Which library would you like to plan to use for the web server?

* [ASP.NET](https://github.com/aspnet/Home)
* [Katana](https://github.com/aspnet/AspNetKatana)
* [LightNode](https://github.com/neuecc/LightNode)
* [Nancy](https://github.com/NancyFx/Nancy)
* or else

**Comment by azyobuzin** [comment]
What I think is that CoreTweet is a platform independent library. So no web platform will be supported (maybe).

If the time comes for me to need a Twitter middleware for ASP.NET Core, I might make a library as another project like [CoreTweetSupplement](https://github.com/CoreTweet/CoreTweetSupplement).

**Comment by cannorin** [comment]
Which library will we use for testing: undetermined. May or may not be the one of those you mentioned.

Which library will we recommend: nothing in particular. CoreTweet is just an API wrapper - nothing more, nothing less.

**Comment by cannorin** [comment]
@azyobuzin Is your Dev Account ready? Today I finally got one.

**Comment by azyobuzin** [comment]
@cannorin not yet :fu:

**Comment by cannorin** [comment]
Implementation ongoing: https://github.com/CoreTweet/CoreTweet/tree/account_activity

**Comment by cannorin** [comment]
Completed: #162
